### ISSUE TITLE
salt models default repository is not available publicly 

### ISSUE THREAD

**Issue by ssfilatov** [Mirantis/tcp-qa#39]
tcp_tests/templates/virtual-mcp11-ovs/salt.yaml:
{% set SALT_MODELS_REPOSITORY = os_env('SALT_MODELS_REPOSITORY','https://gerrit.mcp.mirantis.net/salt-models/mcp-virtual-lab') %}

**Comment by dis-xcom** [comment]
These models are used for internal tests and should not be available for public. Please create a separated repository for your tests.
